# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db1d8a3abd0bc3cc866be4dd7a53ffe84bf4a69566c249d04deeeace206f97d2aa059fcb60c3caee38ef2cf2ac942eaa6f2f620408445d6918fd59088e995b31

test:
  secret_key_base: db71ade258df06e54ced1a6f0c07d60725e18aab6bb3b43c72989bbaf7f89bdd688b60ef2871a07d88dce0420d274a2aa736ae0be5492ed4d43a7fbe5b844189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
